#undef VERSION_STATUS
#undef ENABLE_INTERACTIVE_MODE
#undef ENABLE_VFILE_RPMIO
#undef ENABLE_VFILE_CURL
#undef ENABLE_TRACE
#undef ENABLE_STATIC
#undef HAVE_RPM_4_0
#undef HAVE_RPM_4_0_4
#undef HAVE_RPM_4_1
#undef HAVE_RPM_EXTDEPS
#undef HAVE_READLINE_4_2
#undef HAVE_TM_GMTOFF
#undef HAVE_TM___GMTOFF
#undef HAVE_RPMLOG
#undef HAVE_RPMCHECKSIG

