#!/bin/sh
# $Id$

PATH="/bin:/usr/bin:/usr/sbin:/sbin"
NAME=packages.dir.gz

usage()
{
    echo "usage: `basename $0` [--nodiff] DIR..."
}

if [ "$#" = 0 ]; then
    usage
    exit 1
fi

nodiff=""
while  [ $# -gt 0 ]; do
    if [ "$1" == "--nodiff" ]; then
	nodiff="--nodiff"
	shift
	continue
    fi
	
    if [ ! -d "$1" ]; then
	echo "$1: no such directory"
	exit 1
    fi 
    
    poldek --noconf -s "$1" --mkidxz 

    if [ $? -ne 0 ]; then 
	exit 1
    fi

    if [ ! -f "$1/$NAME" ]; then 
	exit 1
    fi
	
    shift
done    
